# Generated by Django 4.0.4 on 2022-05-24 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scholar_no', models.CharField(max_length=15)),
                ('course_code', models.CharField(max_length=11)),
                ('classes_attended', models.IntegerField()),
                ('classes_total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendance_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_abbr', models.CharField(blank=True, db_column='course_abbr', default='', max_length=20)),
                ('course_credit', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(db_column='dept_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.IntegerField()),
                ('course_code', models.CharField(max_length=10)),
                ('course_dep', models.IntegerField()),
                ('gradescale', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'grading_scale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, unique=True)),
                ('scholar_no', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime(2022, 5, 24, 21, 59, 21, 181089))),
                ('mobile', models.PositiveBigIntegerField()),
                ('parents_mobile', models.PositiveBigIntegerField()),
                ('home_address', models.TextField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(db_column='teacher_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('privilege', models.CharField(max_length=15)),
                ('dept_id', models.IntegerField(blank=True, null=True)),
                ('mobile', models.PositiveBigIntegerField(unique=True)),
                ('blocked', models.IntegerField()),
                ('approved', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
