# Generated by Django 4.0.4 on 2022-09-12 09:53

from django.db import migrations, models
import fireapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(max_length=10, unique=True, validators=[fireapp.models.regex_validators], verbose_name='id'),
        ),
    ]
