# Generated by Django 4.0.4 on 2022-08-29 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('[0-9]{6}-[0-9]{4}', 'only valid student id is required')], verbose_name='uid'),
        ),
    ]
