# Generated by Django 4.0.4 on 2022-05-29 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fireapp", "0002_student_current_semester_student_current_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_semester",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(4),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_year",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(6),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "student_year",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(6),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "student_semester",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(4),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fireapp.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fireapp.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("student", "subject", "student_year", "student_semester")
                },
            },
        ),
    ]
