# Generated by Django 4.0.4 on 2022-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
