# Generated by Django 4.0.4 on 2022-05-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_alter_student_current_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('is_student', 'Student account')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('is_teacher', 'Teacher account')]},
        ),
    ]
