# Generated by Django 4.0.4 on 2022-09-16 09:19

from django.db import migrations, models
import fireapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0004_customuser_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(max_length=11, unique=True, validators=[fireapp.models.regex_validators], verbose_name='id'),
        ),
    ]
