# Generated by Django 4.0.4 on 2022-12-05 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0005_alter_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='average',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
