# Generated by Django 4.0.4 on 2023-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0008_alter_customuser_middle_name_alter_grade_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Teacher'), (3, 'Student')], default=3),
        ),
    ]
